#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "ws2812.pio.h" // This header is automatically generated by CMake!

// The RP2040-Zero has its WS2812 wired to GPIO 16
#define WS2812_PIN 16
#define IS_RGBW false

// Helper function to push color data into the PIO hardware FIFO
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

// Helper function to format Red, Green, and Blue into a single 32-bit GRB word
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return ((uint32_t) (r) << 8) | ((uint32_t) (g) << 16) | (uint32_t) (b);
}

int main() {
    stdio_init_all();

    // Initialize the PIO state machine for the WS2812
    PIO pio = pio0;
    int sm = 0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, sm, offset, WS2812_PIN, 800000, IS_RGBW);

    while (true) {
        // Flash Green
        put_pixel(urgb_u32(0, 50, 0)); // Red=0, Green=50, Blue=0
        sleep_ms(500);

        // Turn Off
        put_pixel(urgb_u32(0, 0, 0));
        sleep_ms(500);
        
        // Flash Blue
        put_pixel(urgb_u32(0, 0, 50)); // Red=0, Green=0, Blue=50
        sleep_ms(500);
        
        // Turn Off
        put_pixel(urgb_u32(0, 0, 0));
        sleep_ms(500);
    }
}