#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "pico/stdlib.h"
#include "pico/stdio_usb.h"
#include "pico/multicore.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "hardware/uart.h"
#include "codec2.h"
#include "i2s_tx.pio.h" // Generated by CMake

#define C2_MODE CODEC2_MODE_1300
#define MAX_SAMPLES_PER_FRAME 320 
#define MAX_CODEC2_BYTES 16

#define UART_BAUD 115200
#define FRAME_SYNC_1 0x55
#define FRAME_SYNC_2 0xD3

// Updated RX Hardware Pins (Must be consecutive!)
#define PIN_UART_RX 5
#define PIN_DAC_DATA 6
#define PIN_DAC_BCLK 7 
#define PIN_DAC_LRCK 8 

volatile bool frame_a_ready = false;
volatile bool frame_b_ready = false;
volatile bool writing_frame_a = true;
volatile uint8_t compressed_frame_a[MAX_CODEC2_BYTES];
volatile uint8_t compressed_frame_b[MAX_CODEC2_BYTES];
int16_t decoded_audio[MAX_SAMPLES_PER_FRAME];

volatile uint32_t dbg_uart_bytes = 0;
volatile uint32_t dbg_frames_crc_ok = 0;
volatile uint32_t dbg_frames_crc_fail = 0;
volatile uint32_t dbg_frames_queued = 0;
volatile uint32_t dbg_frames_dropped = 0;
volatile uint32_t dbg_frames_decoded = 0;
volatile uint32_t dbg_seq_gaps = 0;
volatile uint32_t dbg_sync1_hits = 0;
volatile uint32_t dbg_sync2_hits = 0;
volatile uint32_t dbg_sync2_miss = 0;

static uint8_t codec2_frame_crc(uint8_t seq, const uint8_t *payload, int payload_len) {
    uint8_t crc = seq;
    for (int i = 0; i < payload_len; i++) {
        crc ^= payload[i];
    }
    return crc;
}

// ---------------------------------------------------------
// CORE 1: Codec 2 Decoder & I2S Output
// ---------------------------------------------------------
void core1_entry() {
    struct CODEC2 *c2 = codec2_create(C2_MODE);
    int samples_per_frame = codec2_samples_per_frame(c2);
    int bytes_per_frame = (codec2_bits_per_frame(c2) + 7) / 8;
    if (bytes_per_frame > MAX_CODEC2_BYTES) {
        while (true) {
            tight_loop_contents();
        }
    }

    uint8_t local_compressed_bits[MAX_CODEC2_BYTES];
    
    PIO pio = pio0;
    uint sm = 0;
    uint offset = pio_add_program(pio, &i2s_tx_program);
    
    pio_sm_config c = i2s_tx_program_get_default_config(offset);
    sm_config_set_out_pins(&c, PIN_DAC_DATA, 1);
    
    // Side-set controls both BCLK and LRCK simultaneously
    sm_config_set_sideset_pins(&c, PIN_DAC_BCLK);
    
    // Shift 32-bits out MSB first
    sm_config_set_out_shift(&c, false, true, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    
    // Calculate PIO clock for 8kHz, 64 bits per frame, 2 PIO cycles per bit
    float div = (float)clock_get_hz(clk_sys) / (8000.0f * 64.0f * 2.0f); 
    sm_config_set_clkdiv(&c, div);

    pio_gpio_init(pio, PIN_DAC_DATA);
    pio_gpio_init(pio, PIN_DAC_BCLK);
    pio_gpio_init(pio, PIN_DAC_LRCK);
    pio_sm_set_consecutive_pindirs(pio, sm, PIN_DAC_DATA, 3, true);
    
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);

    while(true) {
        if (frame_a_ready) {
            for (int i = 0; i < bytes_per_frame; i++) {
                local_compressed_bits[i] = compressed_frame_a[i];
            }
            frame_a_ready = false;

            // 1. Inflate the compressed bytes back into raw PCM
            codec2_decode(c2, decoded_audio, local_compressed_bits);
            
            // 2. Push audio to the DAC
            for(int i = 0; i < samples_per_frame; i++) {
                // Cast to 32-bit and shift into the MSB position for the DAC
                uint32_t sample = ((uint32_t)(uint16_t)decoded_audio[i]) << 16;
                
                // PIO expects Left then Right
                pio_sm_put_blocking(pio, sm, sample); // Left Channel
                pio_sm_put_blocking(pio, sm, sample); // Right Channel
            }
            dbg_frames_decoded++;
        }
        else if (frame_b_ready) {
            for (int i = 0; i < bytes_per_frame; i++) {
                local_compressed_bits[i] = compressed_frame_b[i];
            }
            frame_b_ready = false;

            codec2_decode(c2, decoded_audio, local_compressed_bits);

            for (int i = 0; i < samples_per_frame; i++) {
                uint32_t sample = ((uint32_t)(uint16_t)decoded_audio[i]) << 16;
                pio_sm_put_blocking(pio, sm, sample);
                pio_sm_put_blocking(pio, sm, sample);
            }
            dbg_frames_decoded++;
        }
        else {
            tight_loop_contents();
        }
    }
}

// ---------------------------------------------------------
// CORE 0: UART Data Ingestion
// ---------------------------------------------------------
int main() {
    stdio_init_all();
    sleep_ms(1500);
    
    // Listen for the stream from the TX Pico
    uart_init(uart1, UART_BAUD);
    uart_set_format(uart1, 8, 1, UART_PARITY_NONE);
    uart_set_hw_flow(uart1, false, false);
    gpio_set_function(PIN_UART_RX, GPIO_FUNC_UART);
    
    multicore_launch_core1(core1_entry);

    struct CODEC2 *temp_c2 = codec2_create(C2_MODE);
    int bytes_per_frame = (codec2_bits_per_frame(temp_c2) + 7) / 8;
    codec2_destroy(temp_c2);

    if (bytes_per_frame > MAX_CODEC2_BYTES) {
        while (true) {
            tight_loop_contents();
        }
    }

    enum {
        WAIT_SYNC_1,
        WAIT_SYNC_2,
        READ_SEQ,
        READ_PAYLOAD,
        READ_CRC
    } rx_state = WAIT_SYNC_1;

    uint8_t frame_seq = 0;
    uint8_t last_good_seq = 0;
    bool have_last_good_seq = false;
    uint8_t payload[MAX_CODEC2_BYTES];
    uint8_t payload_index = 0;
    uint32_t last_print_ms = to_ms_since_boot(get_absolute_time());

    while(true) {
        uint32_t now_ms = to_ms_since_boot(get_absolute_time());
        if ((now_ms - last_print_ms) >= 1000u) {
            last_print_ms = now_ms;
            if (stdio_usb_connected()) {
                printf("RX bytes=%lu good=%lu badcrc=%lu queued=%lu dropped=%lu decoded=%lu seq_gap=%lu sync1=%lu sync2=%lu sync2miss=%lu readyA=%u readyB=%u\n",
                    (unsigned long)dbg_uart_bytes,
                    (unsigned long)dbg_frames_crc_ok,
                    (unsigned long)dbg_frames_crc_fail,
                    (unsigned long)dbg_frames_queued,
                    (unsigned long)dbg_frames_dropped,
                    (unsigned long)dbg_frames_decoded,
                    (unsigned long)dbg_seq_gaps,
                    (unsigned long)dbg_sync1_hits,
                    (unsigned long)dbg_sync2_hits,
                    (unsigned long)dbg_sync2_miss,
                    frame_a_ready ? 1u : 0u,
                    frame_b_ready ? 1u : 0u);
            }
        }

        if (!uart_is_readable(uart1)) {
            tight_loop_contents();
            continue;
        }

        uint8_t byte_in = uart_getc(uart1);
        dbg_uart_bytes++;

        switch (rx_state) {
            case WAIT_SYNC_1:
                if (byte_in == FRAME_SYNC_1) {
                    dbg_sync1_hits++;
                    rx_state = WAIT_SYNC_2;
                }
                break;

            case WAIT_SYNC_2:
                if (byte_in == FRAME_SYNC_2) {
                    dbg_sync2_hits++;
                    rx_state = READ_SEQ;
                } else if (byte_in != FRAME_SYNC_1) {
                    dbg_sync2_miss++;
                    rx_state = WAIT_SYNC_1;
                }
                break;

            case READ_SEQ:
                frame_seq = byte_in;
                payload_index = 0;
                rx_state = READ_PAYLOAD;
                break;

            case READ_PAYLOAD:
                payload[payload_index++] = byte_in;
                if (payload_index >= bytes_per_frame) {
                    rx_state = READ_CRC;
                }
                break;

            case READ_CRC: {
                uint8_t expected_crc = codec2_frame_crc(frame_seq, payload, bytes_per_frame);
                if (byte_in == expected_crc) {
                    dbg_frames_crc_ok++;
                    if (have_last_good_seq) {
                        uint8_t expected_seq = (uint8_t)(last_good_seq + 1);
                        if (frame_seq != expected_seq) {
                            dbg_seq_gaps += (uint8_t)(frame_seq - expected_seq);
                        }
                    }
                    last_good_seq = frame_seq;
                    have_last_good_seq = true;

                    if (writing_frame_a) {
                        if (!frame_a_ready) {
                            memcpy((void *)compressed_frame_a, payload, bytes_per_frame);
                            frame_a_ready = true;
                            writing_frame_a = false;
                            dbg_frames_queued++;
                        } else {
                            dbg_frames_dropped++;
                        }
                    } else {
                        if (!frame_b_ready) {
                            memcpy((void *)compressed_frame_b, payload, bytes_per_frame);
                            frame_b_ready = true;
                            writing_frame_a = true;
                            dbg_frames_queued++;
                        } else {
                            dbg_frames_dropped++;
                        }
                    }
                } else {
                    dbg_frames_crc_fail++;
                }
                rx_state = WAIT_SYNC_1;
                break;
            }
        }
    }
}